### ISSUE TITLE
Error hashing block (each blocktype)

### ISSUE THREAD

**Issue by madmaxoft** [mrkite/minutor#161]
Windows 64, release 2.2.0 (noinstaller zip). Upon starting, the program displays hundreds of message boxes, each saying "Error hashing block" + blocktype, for each and every blocktype. After discarding each message box, I can open worlds without any apparent problems.

I had an m1.13-branch self-compiled binary working previously, now replaced with the official release executable. I tried clearing all the definitions in `%localappdata%/seancode/Minutor`, that doesn't seem to help.

**Comment by EtlamGit** [comment]
It helps to:

- use Taskmanager to kill these useless message boxes
- delete all definition files in '%localappdata%/seancode/Minutor'
- and delete all pack and packupdate keys in Windows registry
 
Next start of Minutor will repair the definition files.

These messages occur when definitions are loaded twice.

**Comment by madmaxoft** [comment]
Thanks, this fixed the issue, I had no idea about the registry.

Still, the error message is totally unhelpful, even though I new there were _some_ issues with packs, it didn't lead me to success.

**Comment by EtlamGit** [comment]
This error message is only intended for the developer of the definition files. It helps to ensure Block IDs (name strings) do not generate duplicate hashes. It was never intended to be shown to the end user, so it might be a good idea to encapsulate it with `#ifdef DEBUG`

But a real fix would prevent this strange double loading case. I have no real clue what is triggering this case, but I have the same issue occasionally during development.
I plan to add some code to check if user data store and registry have the same definition files. And otherwise, try to correct that somehow.

If you could describe a scenario to trigger this case, we have something to debug deeper...

**Comment by STrRedWolf** [comment]
FYI in Linux the directory to clear out is ~/.local/share/seancode/Minutor
