### ISSUE TITLE
Minutor v2.3.0 crashes while scrolling around map

### ISSUE THREAD

**Issue by archiesholland** [mrkite/minutor#192]
Minutor v2.3.0 crashes while scrolling around map.

[Report.wer.txt](https://github.com/mrkite/minutor/files/3894765/Report.wer.txt)
[Report1.wer.txt](https://github.com/mrkite/minutor/files/3894766/Report1.wer.txt)

**Comment by EtlamGit** [comment]
Are you using the latest build or an ancient release?

**Comment by archiesholland** [comment]
Latest build, from https://www.dropbox.com/s/c9n320hjet3hdjf/minutor.zip?dl=0

Archie S. Holland
Archie/Brother/Dad/Uncle/Grandpa
archiesholland@gmail.com
home: 270-765-2530
cell: 270-763-7530

"Shared pain is diminished - shared joy is increased"
------Mike Callahan

**Comment by EtlamGit** [comment]
The nightly changed 2-3 days ago. Do you use that new version?

Is this crash only for one special world? Or even for new created worlds?
If only on world, please provide the world,

On what zoom level do you scroll and crash?
Do you use the new zoom out feature. (still unstable, so disable for the moment)

What about your RAM and overall memory usage?
Do you use a 64bit operation system?
32bit Windows will not provide enough memory for larger window size.
Is your monitor too large or your RAM too small?

**Comment by archiesholland** [comment]
Yes, I'm using that newest version.
I've only used it on one world so far. (attached)
Using the default zoom level (didn't know there WAS a new zoom out feature)
(grin)
Windows 10 Pro
Version 10.0.17763 Build 17763
Dell Inc. Inspiron 5558
x64-based PC
Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz, 2401 Mhz, 2 Core(s), 4 Logical
Processor(s)
Installed Physical Memory (RAM) 8.00 GB
Total Physical Memory 7.91 GB
Available Physical Memory 4.13 GB
Total Virtual Memory 10.3 GB
Available Virtual Memory 5.46 GB
Page File Space 2.38 GB
NVIDIA GeForce 920M
Intel HD Graphics 5500

Just noticed that it only seems to occur at edges of the map.

 World36.zip
<https://drive.google.com/file/d/10ql51hQY4lq9FWDvHiuTg7xVDRCDRhwZ/view?usp=drive_web>

Archie S. Holland
Archie/Brother/Dad/Uncle/Grandpa
archiesholland@gmail.com
home: 270-765-2530
cell: 270-763-7530

"Shared pain is diminished - shared joy is increased"
------Mike Callahan

**Comment by EtlamGit** [comment]
Your world seem to be ok. At least it renders without problems here.

Your RAM is a bit low. The only memory that counts is available physical memory. Other kind of memory does not help for Minutor.
What you can try is:

- close other applications **before** starting Minutor
- use only smaller window size

I plan to add some code to prevent out-of-memory crashes in the next weeks.

I have added a debug build to the [Nightly Page](https://github.com/mrkite/minutor/wiki/Nighlty-Builds). This version shows Chunk Cache usage and total size in the lower status bar. Maybe you can observe that your usage hits the total size right before the crash?

**Comment by EtlamGit** [comment]
By the way: as you are responding via Email, your footer gets copied here to GitHub too.
I will always edit your comments to remove your private telephone number.

**Comment by archiesholland** [comment]
Running minutor_debug gave some odd results.
First, it very rarely crashes now, even with lots of scrolling and
maximized screen.
When running minutor_debug only, cache size was 35673.  It took several
minutes of scrolling around before it used all the cache, and even then it
didn't crash immediately.
Ran it multiple times, adding in more apps each time. Still only crashed
sometimes.
Final test was running Chrome with multiple tabs open, Minecraft, Amidst
and finally minutor_debug. Cache size is now 11536, all in use.
In all cases, cache was 100% before it crashed.

Hope that helps.

**Comment by EtlamGit** [comment]
Hi @cre4ture as you did already some nice stability improvements in the last time, this is maybe something you can solve?
My assumption is, that we:
 - open a large map, scroll to one side and therefore schedule many Chunks to be loaded and rendered
 - now scroll to the other side and demand more Chunks than fit in the ChunkCache
 - this may lead to Chunks being thrown out of the ChunkCache and deleted before loaded and rendered completely

**Comment by cre4ture** [comment]
Hi EtlamGit,
your request encouraged me to check the issue shortly. Actually I wasn't able to reproduced it. But I reviewed the code regarding the ChunkCache and found a potential issue. You can see it in the pull request I just created. Ideally archiesholland could test if it helps him. Can you provide him binaries?

**Comment by EtlamGit** [comment]
[Binaries are updated.](https://github.com/mrkite/minutor/wiki/Nighlty-Builds)

**Comment by archiesholland** [comment]
Using the same map as before, I capped out at 26582/26582.  Scrolled around
for about ten minutes with no issues.
Also tried it on a small 1.15 (just released) map, hit 26535/26535, still
no issues.

Archie S. Holland

**Comment by archiesholland** [comment]
Just tried it again, whilst running Chrome with multiple tabs, Minecraft,
Task Manager and Amidst.  Hit 12520/12520, still no issues.  (But my poor
computer was running at 80%+ memory the whole time.  Hopefully I'll get
some more ram for Christmas.)

Archie S. Holland
Archie/Brother/Dad/Uncle/Grandpa
archiesholland@gmail.com
home: 270-765-2530
cell: 270-763-7530

"Shared pain is diminished - shared joy is increased"
------Mike Callahan

**Comment by EtlamGit** [comment]
Christmas is a good choice for new RAM. It is expected to get more expensive during next year.

**Comment by Landmine752** [comment]
Chiming in for the same issue with additional information. Minutor will crash when scrolling too fast and viewing undiscovered chunks. I've even tested a small map (tested on a diagonal-shaped world ~1500x~1100) and encountered this regardless of window size.

The more I test, the less predictable this crash seems to be (and, after more testing and writing this, Minutor actually seems more stable).

Interestingly, I've never crashed on discovered-only chunks; it may take awhile to load, but it will load none-the-less. Using the debug build, I have observed the cache reaching ~11k and ~24k (of ~60k) before crashing, but only when a notable amount of undiscovered chunks are involved (guessing around 1/8th of the screen @ full-screen). If I scroll slow and the stars are happy, I have reached ~110k (before scrolling faster and crashing). The crash may be related to scroll speed/window size, but I've also crashed scrolling slowly on the small map at the default window size. Which leads me to a second observation...

If a world crashes, you'll probably end up crashing in that same spot. Again, this isn't a very predictable crash, but after crashing my small world, it would keep crashing in the same spot if I went directly there (even at default window size). Only after taking a slightly different route (going from the East instead of the South) did it stop crashing there.

Now the small world does not seem to crash at all. Same with the other (much larger) worlds I've reloaded and successfully navigated without crashing; I cannot crash them anymore even by doing the same thing that would previously cause a crash.

For completions sake, I'm running:
Processor: Intel i7-4790 CPU @ 4GHz
RAM: 16GB
Windows 10 (64 bit) Build 18362
Graphics: Nvidia GeForce GTX 980
Averaging 35% Mem. usage (without Minutor) throughout my tests. The issue may still be related to RAM, but a few of the quirks I've described make me think there may be more to this.
