### ISSUE TITLE
2.20 Crashes upon opening world file. (Linux Mint 20.1)

### ISSUE THREAD

**Issue by LaggyAsBalls** [mrkite/minutor#249]
Installed with the .deb, I open a world file and it crashes.

`qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
Unhandled toInt
Unhandled toInt
Unhandled length
Unhandled length
Unhandled toLongArray
Unhandled length
Unhandled toByteArray
Segmentation fault (core dumped)
`

I'm also unable to install the nightly from [here](https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aminutor&package=minutor)

Despite having the dependency installed, it tells me it is not satisfiable. 

![why](https://user-images.githubusercontent.com/51206257/115946560-462ba780-a47f-11eb-9332-e872a12319ce.png)

**Comment by EtlamGit** [comment]
Minutor 2.20 is very very old.
Minecraft changed storage format many times since that release. So that will work only for older Minecraft versions.
Which Minecraft version are you using?

Use a recent build:
https://github.com/mrkite/minutor/wiki/Nightly-Builds
https://github.com/mrkite/minutor/actions

The build from Nick is not official, but should work. The error message indicates for me that you have to install Qt 5.15.1 or later. Try one of our nightly builds with lower Qt requirement. Or compile yourself, it is easy on Linux (at least compared to Windows).

**Comment by EtlamGit** [comment]
Linux Mint 20 is based on Ubuntu 20.04.
An there the official supported Qt is 5.12. This is reflected by our build chain.

**Comment by LaggyAsBalls** [comment]
Latest version. 1.16.5

**Comment by EtlamGit** [comment]
1.16.5 should work with nightly.
At least here on Windows it is working. Also no crash with upcoming 1.17.

**Comment by Kolcha** [comment]
@LaggyAsBalls Did you downloaded package / added repo for Ubuntu 20.04 from [mentioned link (my repo)](https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aminutor&package=minutor)?
looks like you downloaded package for some very new Ubuntu **21**.04 or Debian unstable... only few distros have Qt 5.15 nowadays.
[Ubuntu 20.04 comes with Qt 5.12](https://packages.ubuntu.com/focal/qtbase5-dev), and I use only system libraries for build. Also I checked that [package for Ubuntu **20**.04](https://download.opensuse.org/repositories/home:/nikoneko:/minutor/xUbuntu_20.04/amd64/minutor_2.2.0+171~fc709ae-0+25.1_amd64.deb) has correct dependencies: `libqt5core5a (>= 5.12.2)`. also I recommend to add repo instead of downloading package, package is updated when new commits appear

**Comment by EtlamGit** [comment]
@LaggyAsBalls is your issue solved?
