### ISSUE TITLE
Error opening build 5.12 on OsX

### ISSUE THREAD

**Issue by Macfelon** [mrkite/minutor#253]
Build 5.12, on OsX, I get an endless repeating dialog box with "Failed to add Block from definition file, as it might be a duplicate
or generates the same hash as an already existing Block."

**Comment by EtlamGit** [comment]
You probably have used different versions of Minutor at the same time.
Recent Minutor should try to solve this issue automatically.

**Root cause is that you have multiple definition files, defining the same Blocks.**

You should try to clean up your definition files: delete them all
(Minutor will restore the latest one at next start)

I have no clue where to find these files on OSX, maybe you find hints in similar issues:
#35 #107 #108 #157 #161 #165 #188 #193

And afterwards, do not start an ancient version of Minutor again (or repeat deleting).

**Comment by Macfelon** [comment]
Dead on, it was the Manage Packs under View menu.  It is working as expected now.  Thanks!  (I have removed all previous versions of the application).
