### ISSUE TITLE
Black "voids" on map

### ISSUE THREAD

**Issue by ShortMiner01** [mrkite/minutor#279]
Firstly, I want to tell you how your program has helped my grandson and I with our "Project".. We LOVE Minutor!! <3

I have been using Minutor for a couple of years now with no issues but suddenly I'm getting black "voids" on my map.. Did I do something to make this happen? I have the same PC and just updated our project to Minecraft-1.18.. Minutor has been working perfectly until now
[Minutor Screenshot Bug](https://user-images.githubusercontent.com/72843837/150025217-bf38f912-2e18-45cd-a124-ff939b7fda10.jpg)

Thank you :)

**Comment by EtlamGit** [comment]
For me it looks like Minecraft has not updated these parts of the map. Or something went wrong during map update.
* Depth slider shows 191 as default height, so I assume you have the latest released version of Minutor and your world has been detected as 1.18 world. -> fine
* Black areas are Chunks that are not processed completely by Minecraft. That is normal at the borders of render distance. E.g. if you have traveled in that world to the location a little bit above the current view but horizontally in the middle, I could explain the black areas in the upper area. -> look bad, but is maybe ok
* Grayed out Chunks are missing ones. This happens when Minecraft has not stored them properly. E.g. when you start Minutor while Minecraft is still running. -> look bad, but is maybe ok

What I would propose is:
* Play Minecraft and travel to these locations. Travel in circles or regular strips, so that Minecraft is able to convert all area to new 1.18 storage format. Use strip distance lower than your render distance so that no holes are left.
* While traveling, observe the terrain for strange looking things. When it looks fine in Minecraft, it should look fine in Minutor too. Look at the same location in Minecraft and Minutor!
* When your server is local, ensure some time for proper save. In case of remote/rented server, also give it time to save your new world data (autosave is only every hour).
* Use Minutor to export your complete world as PNG image. Upload that image here. I would be interested in other areas of the map.
* ZIP your complete world and upload it here for me to debug. (think before if there is some private stuff you do not want to share, or find a way that only I can download/open that zipped file)

**Comment by EtlamGit** [comment]
@ShortMiner01 any update?

**Comment by ShortMiner01** [comment]
Yes sir, thank you for your reply.. I'm sorry, I've been having family
issues and haven't had a chance to follow your recommendations.. I will
open Minutor this afternoon when I get home and see what I find out

Once again, thank you for your reply and my Grandson and I LOVE your Minutor
We've been playing Minecraft for many years when I used to babysit him
after school.. Of course, e has graduated to Fort Nite, Madden and Special
Ops.. He's 18 now and when he comes over I like to show him my progress on
the world we created, and he's so proud of Granny :)

Have a great day and God Bless

**Comment by ShortMiner01** [comment]
I wanted to drop you a note and tell you that you were absolutely right.. I
flew all over the black "voids" of my map and Minutor filled in my map.. I
found places I never knew existed, like a lost underwater City of Atlantis
:)

Anyway, thank you for responding to my feedback.. You guys are awesome!! :)
