### ISSUE TITLE
Biome File example

### ISSUE THREAD

**Issue by drakray** [mrkite/minutor#298]
Hi, is there a template for modded biomes?
I can't seem to make it work, mainly for BiomesOPlenty and Graveyard

Thanks :D

**Comment by drakray** [comment]
For 1.18.1, I should specify lol

**Comment by EtlamGit** [comment]
There is a [readme](https://github.com/mrkite/minutor/blob/master/definitions/readme_biomes.txt) describing how it was done in the past . . .

For 1.18 specific Biomes it is the same, just use "data18" as tag instead of "data".
Difference is that "id" is now a string.
If you intend to be backwards compatible with older Minutor versions you have to fill both tags.

Maybe you can paste some intermediate (non-working) version here?

**Comment by drakray** [comment]
Yeah I use to manually make Biome Definition all the time back then, no problem with that lol
I don't need the backward compatible, just 1.18.1

I have this.
[Modded Biomes.json.txt](https://github.com/mrkite/minutor/files/8523024/Modded.Biomes.json.txt)
Without the definition, Minutor show modded biome as "Unknown", in black(CTRL+B)
With the definition, it shows vanilla biome, like what is supposed to be BOP Wasteland is Jagged or Frozen Peak, and Spider Nest is Warped Forest

Also removing the definition and F5 or F2 don't revert to black Unknown Biome, I must restart Minutor to "fix"

**Comment by EtlamGit** [comment]
Ah, ok you do not have issues with the format itself . . .
I'm able to add your definition. While debugging that step, it also looks fine, an additional set of Biomes is created internally. They are also put to the list of enabled Biomes. In theory it should work . . .

Comments:
* You can use a tag "name" to provide a name used for display purpose. Otherwise it would be guessed from the "id". Meaning id":"biomesoplenty:bamboo_grove" will result in "biomesoplenty:bamboo Grove". (But probably I should enhance this guessing.)
*  "version": "Forge 1.18.1" looks strange for me. Probably it will work, but it is a format I would not have expected. Expected would by only numbers for major and minor, numbers or week descriptions for patch, no spaces at all, 2 dots to separate <major>.<minor>.<patch> (Probably not the root cause of your problem.)

I do not play modded Minecraft. Could you please provide a small test world for debugging?

**Comment by drakray** [comment]
http://www.drakray.com:81/MC/1.18/New%20World.zip

Included my ModdedDefinition, and my minutor.exe

The "name" tag in data18 will be somewhat useful, but not essential. I'll probably just reuse my [data] listing, I like to have modName before biomeName lol

**Comment by EtlamGit** [comment]
Bug found & fixed: Biomes are now stored with a self generated index. And minecraft:frozen_peaks and biomesoplenty:wasteland both had id==59

I will publish a fix later. Other possible bugs are in nearby code.
