### ISSUE TITLE
Increase/remove limit for search results

### ISSUE THREAD

**Issue by pinexd** [mrkite/minutor#300]
Currently, when I use the search feature for blocks, minutor will find blocks until it reaches 16001 results, at which point it will continue "searching" (the progress bar will continue), but no more results will be added to the list. I think it would be beneficial to raise or remove this limit if possible, as it would be useful for finding an accurate count of each block in a world.

**Comment by EtlamGit** [comment]
You "can" search for stone or even air.
For each found Block a memory structure is stored and an entry in this result list is created.
You are even able to highlight all found Blocks on the map.
And a world can be very large too.

-> So you will blow up your RAM in a very short time and the UI will freeze.
I just tested it with raising the limit: RAM usage looks ok, but with that many results in a scroll list the UI get unusable.


With that in mind, it is clear, that we need some sort of upper limit.

Maybe you describe more **what** you intend to do. In most cases there are other solutions that work better.
E.g. if you are interested in the amount of diamond_ore Blocks in a world, it is better to count them instead of filling a extreme long list with all their coordinates.

**Comment by pinexd** [comment]
Thanks for the quick response, I appreciate it & I appreciate your work. The example you described is exactly what I'm going for. I want to find the **amount** of a certain block in the world, not necessarily the coordinates of them. If there's anything that can be done to accommodate that, I'd be forever grateful. Thank you.

**Comment by EtlamGit** [comment]
There is some example I did when 1.18 was in development:
Measure the ore distribution along the Y axis and how this changed during the snap shots. This is similar to the figures you find in the Minecraft Wiki, but at a time they are not updated there. I modified a local Minutor version to export that data as it was just to see progress during the snapshot phase.
My (mid or long term) plan would be to add something directly in Minutor. But you should not expect it before next vacation period.

Another remark: amount of something per world is not a fixed or defined value. As the world may have any size or even increase in size from one measure to the next, the numbers are not comparable. You should try to get amount of something per N Sections or per N Chunks.

**Comment by pinexd** [comment]
I think you may be misunderstanding my intent, so let me explain a little bit more in depth. I have the world save of an SMP server I played on last year, and I am trying to find the amount of blocks (i.e Spruce Planks) in the world (which is limited to a 5k radius from 0, 0).

**Comment by EtlamGit** [comment]
Progress update:
![grafik](https://user-images.githubusercontent.com/5821779/195984860-08045d07-f28f-4840-acdd-7bfec2aca58e.png)
