### ISSUE TITLE
[Windows] Error loading Block definition: minecraft:air

### ISSUE THREAD

**Issue by J-Cena** [mrkite/minutor#305]
Always get the following error on launch:

Error loading Block definition: minecraft:air
Failed to add Block from definition file, as it might be a duplicate or generated the same hash as an already existing Block.

Only option is 'Cancel' which just opens the same message again (can only close with Task Manager).

I performed Windows updates, updated Visual C++ Redistributable, updated Java, reinstalled Minecraft and tried on another Windows 10 machine (the Linux version did end up working though).

**Comment by EtlamGit** [comment]
This means your definition files got messed up (duplicate definition for same type of block).
In most cases the reason is a very outdated version of Minutor or mixed use of different versions.

**!!! Important: please read last sentence before deleting anything !!!**

There are multiple ways to solve this:
* go through the click hell and click cancel for all duplicated blocks, after that the self repair should have healed it
* delete your broken definition files:
  they are located in temporary user folder C:\Users\J-Cena\AppData\Local\seancode\Minutor
  it is save to delete the complete folder Minutor or seancode

Could you please zip this folder before deleting. Then paste it here. This way I could try to debug the situation and improve self repair functionality.

**Comment by J-Cena** [comment]
Deleting the folder fixed the issue. Thanks a lot.

I also zipped it like you requested


[seancode.zip](https://github.com/mrkite/minutor/files/8845490/seancode.zip)
.

**Comment by J-Cena** [comment]
Yes, that is correct. I have previously used older versions.
