### ISSUE TITLE
Increase zoom

### ISSUE THREAD

**Issue by piegamesde** [mrkite/minutor#97]
I'd like to be able to zoom out further on some really large maps. Related features:

- Cache rendered Data to avoid re-rendering
- Low-res rendering for fast loading preview and RAM saving when zoomed out.

But just zooming out would already help me a lot.

**Comment by madmaxoft** [comment]
That would be rather problematic to stuff it all into the RAM. A regular FullHD display has 1920x1080 pixels, with 100% zoom this means at least resolution * vertical size * bytes per block = 1920 * 1080 * 256 * 3 = about 1518 MiB of RAM. Halving the zoom in the same display resolution would consume at least four times that much RAM. Of course there are savings, such as not storing empty sub-chunks, but those won't save you at all times and are only linear, in contrast to the quadratic growth of RAM requirements.

For large maps, a PNG export is probably a better solution for you.

**Comment by EtlamGit** [comment]
Despite extreme RAM usage (which could be solved with buying larger modules), there is a much more important point: when zoomed out to the current maximum, Minutor displays one block per screen pixel.

If you now intend to zoom out more, you have to combine multiple blocks in one pixel and you would loose much of the detail. A strategy for combining (averaging/blurring) would also be necessary.

I would also recommend PNG export and usage of a image viewer that is dedicated for showing large images. Another solution is to buy a larger monitor... e.g. 4k

**Comment by piegamesde** [comment]
Wow, so the program

 - Always loads the whole chunk data (& keeps it in RAM)
 - And renders it in real time
 - without texture filtering

?
No wonder zooming out more won't work. I thought it was like AMIDST with a simple zoom cap you can change if the machine has enough RAM.

**Comment by EtlamGit** [comment]
"won't work" is a bit hard, but it would need some extra code to handle that "combining". Not very complicated, but it has to be tested for corner cases.
The biggest problem is that Minutor (32bit) already now has RAM problems with 1920x1080 monitors. So I would expect random crashes and instabilities. And I would like to avoid that normal users encounter these problems every day...

**Comment by AdriaanRenting** [comment]
I suggest using AMIDST if you're looking for biomes or other map features.
I suggest making screenshots and putting them together in some kind of image editing program if you have a really large world map you want to make.
I don't think minutor is designed for this. Use a tool suitable for what you want to do.

**Comment by piegamesde** [comment]
This is now two and a half years old. I've since made my own map renderer, which focuses on handling huge worlds on large zoom factors.

Feel free to close this if you don't plan to implement it.

**Comment by cre4ture** [comment]
Hi guys and @piegamesde , as usual the one that needs it has to do it himself.

I just put my adapted version of minutor on my github:
https://github.com/cre4ture/minutor
It has support for larger zoom levels, tweaked multithreaded loading and rendering and some other neat extensions like searching for villagers (entities in general) selling certain desired stuff (like enchanted books and so on). Also you can search for rare blocks (like pumkins, melons or chests). Be carefull, I disabled the feature that flushes cached chunks when they are not displayed. That means you really need a machine with a lot RAM - and of course 64 bit compiler. In my case 16 GBs where enougth, but I also don't have very large maps.

@mrkite : I'm writing here only because I think it would be cool to bring some of those features (search enchanted book sellers, large zoom, follow players, correct positioning of players in nether on overworld, refactorings, ...) to your master. But I guess you have to help me as I'm not yet used to git very much and also quite new to GitHub. I guess also my submits where not very clean so that a merge is easily possible. At least I updated my branch with the latest master changes from your side. But I'm not sure if every feature still works as desired from your side. It's more a "hacking" branch for my personal demands.

**Comment by IronException** [comment]
@cre4ture it would be dope to have these features in the official version of minutor. Where do you need help? if you merged this version with your already you should also be able to create a pull request

**Comment by cre4ture** [comment]
#186 is probably what is needed here. At least one first step.

**Comment by EtlamGit** [comment]
Feature is integrated.
